export const OBTENER_POKEMONES_EXITO= "OBTENER_POKEMONES_EXITO"
export const DECREMENTAR = "DECREMENTAR";
export const SIGUIENTE_POKEMONES_EXITO= "SIGUIENTE_POKEMONES_EXITO";
export const RETROCEDER_POKEMONES_EXITO= "RETROCEDER_POKEMONES_EXITO";